#!/bin/bash
source catkin_my_mavros/devel/setup.bash

DIR="$(rospack find my_mavros)/recordings/default/recording.bag" #Donde se guarda la grabación

NS0="/uav0/"    #Namespace del dron
NS1="/uav1/"
NS2="/uav2/"
NS3="/uav3/"

C="camera/color/image_raw"      #Topics a leer
CI="camera/color/camera_info"
D="camera/depth/image_raw"
DI="camera/depth/camera_info"

UAV0="${NS0}${C} ${NS0}${CI} ${NS0}${D} ${NS0}${DI}"
UAV1="${NS1}${C} ${NS1}${CI} ${NS1}${D} ${NS1}${DI}"
UAV2="${NS2}${C} ${NS2}${CI} ${NS2}${D} ${NS2}${DI}"
UAV3="${NS3}${C} ${NS3}${CI} ${NS3}${D} ${NS3}${DI}"

TOPICS="/tf /tf_static ${UAV0} ${UAV1} ${UAV2} ${UAV3}"

#Ejecución
rosbag record -b 1024 -O $DIR $TOPICS


# /clock
# /diagnostics
# /gazebo/link_states
# /gazebo/model_states
# /gazebo/parameter_descriptions
# /gazebo/parameter_updates
# /gazebo/performance_metrics
# /gazebo/set_link_state
# /gazebo/set_model_state
# /gps/fix
# /imu/data
# /rosout
# /rosout_agg
# /tf
# /tf_static
# /uav0/camera/color/camera_info
# /uav0/camera/color/image_raw
# /uav0/camera/color/image_raw/compressed
# /uav0/camera/color/image_raw/compressed/parameter_descriptions
# /uav0/camera/color/image_raw/compressed/parameter_updates
# /uav0/camera/color/image_raw/compressedDepth
# /uav0/camera/color/image_raw/compressedDepth/parameter_descriptions
# /uav0/camera/color/image_raw/compressedDepth/parameter_updates
# /uav0/camera/color/image_raw/theora
# /uav0/camera/color/image_raw/theora/parameter_descriptions
# /uav0/camera/color/image_raw/theora/parameter_updates
# /uav0/camera/depth/camera_info
# /uav0/camera/depth/image_raw
# /uav0/camera/depth/points
# /uav0/camera_ir/parameter_descriptions
# /uav0/camera_ir/parameter_updates
# /uav0/mavlink/from
# /uav0/mavlink/gcs_ip
# /uav0/mavlink/to
# /uav0/mavros/actuator_control
# /uav0/mavros/adsb/send
# /uav0/mavros/adsb/vehicle
# /uav0/mavros/altitude
# /uav0/mavros/battery
# /uav0/mavros/cam_imu_sync/cam_imu_stamp
# /uav0/mavros/companion_process/status
# /uav0/mavros/debug_value/debug
# /uav0/mavros/debug_value/debug_vector
# /uav0/mavros/debug_value/named_value_float
# /uav0/mavros/debug_value/named_value_int
# /uav0/mavros/debug_value/send
# /uav0/mavros/esc_info
# /uav0/mavros/esc_status
# /uav0/mavros/estimator_status
# /uav0/mavros/extended_state
# /uav0/mavros/fake_gps/mocap/tf
# /uav0/mavros/geofence/waypoints
# /uav0/mavros/global_position/compass_hdg
# /uav0/mavros/global_position/global
# /uav0/mavros/global_position/gp_lp_offset
# /uav0/mavros/global_position/gp_origin
# /uav0/mavros/global_position/home
# /uav0/mavros/global_position/local
# /uav0/mavros/global_position/raw/fix
# /uav0/mavros/global_position/raw/gps_vel
# /uav0/mavros/global_position/raw/satellites
# /uav0/mavros/global_position/rel_alt
# /uav0/mavros/global_position/set_gp_origin
# /uav0/mavros/gps_rtk/rtk_baseline
# /uav0/mavros/gps_rtk/send_rtcm
# /uav0/mavros/gpsstatus/gps1/raw
# /uav0/mavros/gpsstatus/gps1/rtk
# /uav0/mavros/gpsstatus/gps2/raw
# /uav0/mavros/gpsstatus/gps2/rtk
# /uav0/mavros/hil/actuator_controls
# /uav0/mavros/hil/controls
# /uav0/mavros/hil/gps
# /uav0/mavros/hil/imu_ned
# /uav0/mavros/hil/optical_flow
# /uav0/mavros/hil/rc_inputs
# /uav0/mavros/hil/state
# /uav0/mavros/home_position/home
# /uav0/mavros/home_position/set
# /uav0/mavros/imu/data
# /uav0/mavros/imu/data_raw
# /uav0/mavros/imu/diff_pressure
# /uav0/mavros/imu/mag
# /uav0/mavros/imu/static_pressure
# /uav0/mavros/imu/temperature_baro
# /uav0/mavros/imu/temperature_imu
# /uav0/mavros/landing_target/lt_marker
# /uav0/mavros/landing_target/pose
# /uav0/mavros/landing_target/pose_in
# /uav0/mavros/local_position/accel
# /uav0/mavros/local_position/odom
# /uav0/mavros/local_position/pose
# /uav0/mavros/local_position/pose_cov
# /uav0/mavros/local_position/velocity_body
# /uav0/mavros/local_position/velocity_body_cov
# /uav0/mavros/local_position/velocity_local
# /uav0/mavros/log_transfer/raw/log_data
# /uav0/mavros/log_transfer/raw/log_entry
# /uav0/mavros/manual_control/control
# /uav0/mavros/manual_control/send
# /uav0/mavros/mission/reached
# /uav0/mavros/mission/waypoints
# /uav0/mavros/mocap/pose
# /uav0/mavros/mount_control/command
# /uav0/mavros/mount_control/orientation
# /uav0/mavros/obstacle/send
# /uav0/mavros/odometry/in
# /uav0/mavros/odometry/out
# /uav0/mavros/onboard_computer/status
# /uav0/mavros/param/param_value
# /uav0/mavros/play_tune
# /uav0/mavros/px4flow/ground_distance
# /uav0/mavros/px4flow/raw/optical_flow_rad
# /uav0/mavros/px4flow/raw/send
# /uav0/mavros/px4flow/temperature
# /uav0/mavros/radio_status
# /uav0/mavros/rallypoint/waypoints
# /uav0/mavros/rc/in
# /uav0/mavros/rc/out
# /uav0/mavros/rc/override
# /uav0/mavros/setpoint_accel/accel
# /uav0/mavros/setpoint_attitude/cmd_vel
# /uav0/mavros/setpoint_attitude/thrust
# /uav0/mavros/setpoint_position/global
# /uav0/mavros/setpoint_position/global_to_local
# /uav0/mavros/setpoint_position/local
# /uav0/mavros/setpoint_raw/attitude
# /uav0/mavros/setpoint_raw/global
# /uav0/mavros/setpoint_raw/local
# /uav0/mavros/setpoint_raw/target_attitude
# /uav0/mavros/setpoint_raw/target_global
# /uav0/mavros/setpoint_raw/target_local
# /uav0/mavros/setpoint_trajectory/desired
# /uav0/mavros/setpoint_trajectory/local
# /uav0/mavros/setpoint_velocity/cmd_vel
# /uav0/mavros/setpoint_velocity/cmd_vel_unstamped
# /uav0/mavros/state
# /uav0/mavros/statustext/recv
# /uav0/mavros/statustext/send
# /uav0/mavros/target_actuator_control
# /uav0/mavros/time_reference
# /uav0/mavros/timesync_status
# /uav0/mavros/trajectory/desired
# /uav0/mavros/trajectory/generated
# /uav0/mavros/trajectory/path
# /uav0/mavros/vfr_hud
# /uav0/mavros/vision_pose/pose
# /uav0/mavros/vision_pose/pose_cov
# /uav0/mavros/vision_speed/speed_twist_cov
# /uav0/mavros/wind_estimation
# /uav0/rtabmap/cloud_ground
# /uav0/rtabmap/cloud_map
# /uav0/rtabmap/cloud_obstacles
# /uav0/rtabmap/global_path
# /uav0/rtabmap/global_path_nodes
# /uav0/rtabmap/global_pose
# /uav0/rtabmap/goal
# /uav0/rtabmap/goal_node
# /uav0/rtabmap/goal_out
# /uav0/rtabmap/goal_reached
# /uav0/rtabmap/grid_map
# /uav0/rtabmap/grid_prob_map
# /uav0/rtabmap/info
# /uav0/rtabmap/initialpose
# /uav0/rtabmap/labels
# /uav0/rtabmap/landmarks
# /uav0/rtabmap/local_grid_empty
# /uav0/rtabmap/local_grid_ground
# /uav0/rtabmap/local_grid_obstacle
# /uav0/rtabmap/local_path
# /uav0/rtabmap/local_path_nodes
# /uav0/rtabmap/localization_pose
# /uav0/rtabmap/mapData
# /uav0/rtabmap/mapGraph
# /uav0/rtabmap/mapPath
# /uav0/rtabmap/octomap_binary
# /uav0/rtabmap/octomap_empty_space
# /uav0/rtabmap/octomap_full
# /uav0/rtabmap/octomap_global_frontier_space
# /uav0/rtabmap/octomap_grid
# /uav0/rtabmap/octomap_ground
# /uav0/rtabmap/octomap_obstacles
# /uav0/rtabmap/octomap_occupied_space
# /uav0/rtabmap/proj_map
# /uav0/rtabmap/scan_map
# /uav1/camera/color/camera_info
# /uav1/camera/color/image_raw
# /uav1/camera/color/image_raw/compressed
# /uav1/camera/color/image_raw/compressed/parameter_descriptions
# /uav1/camera/color/image_raw/compressed/parameter_updates
# /uav1/camera/color/image_raw/compressedDepth
# /uav1/camera/color/image_raw/compressedDepth/parameter_descriptions
# /uav1/camera/color/image_raw/compressedDepth/parameter_updates
# /uav1/camera/color/image_raw/theora
# /uav1/camera/color/image_raw/theora/parameter_descriptions
# /uav1/camera/color/image_raw/theora/parameter_updates
# /uav1/camera/depth/camera_info
# /uav1/camera/depth/image_raw
# /uav1/camera/depth/points
# /uav1/camera_ir/parameter_descriptions
# /uav1/camera_ir/parameter_updates
# /uav1/mavlink/from
# /uav1/mavlink/gcs_ip
# /uav1/mavlink/to
# /uav1/mavros/actuator_control
# /uav1/mavros/adsb/send
# /uav1/mavros/adsb/vehicle
# /uav1/mavros/altitude
# /uav1/mavros/battery
# /uav1/mavros/cam_imu_sync/cam_imu_stamp
# /uav1/mavros/companion_process/status
# /uav1/mavros/debug_value/debug
# /uav1/mavros/debug_value/debug_vector
# /uav1/mavros/debug_value/named_value_float
# /uav1/mavros/debug_value/named_value_int
# /uav1/mavros/debug_value/send
# /uav1/mavros/esc_info
# /uav1/mavros/esc_status
# /uav1/mavros/estimator_status
# /uav1/mavros/extended_state
# /uav1/mavros/fake_gps/mocap/tf
# /uav1/mavros/geofence/waypoints
# /uav1/mavros/global_position/compass_hdg
# /uav1/mavros/global_position/global
# /uav1/mavros/global_position/gp_lp_offset
# /uav1/mavros/global_position/gp_origin
# /uav1/mavros/global_position/home
# /uav1/mavros/global_position/local
# /uav1/mavros/global_position/raw/fix
# /uav1/mavros/global_position/raw/gps_vel
# /uav1/mavros/global_position/raw/satellites
# /uav1/mavros/global_position/rel_alt
# /uav1/mavros/global_position/set_gp_origin
# /uav1/mavros/gps_rtk/rtk_baseline
# /uav1/mavros/gps_rtk/send_rtcm
# /uav1/mavros/gpsstatus/gps1/raw
# /uav1/mavros/gpsstatus/gps1/rtk
# /uav1/mavros/gpsstatus/gps2/raw
# /uav1/mavros/gpsstatus/gps2/rtk
# /uav1/mavros/hil/actuator_controls
# /uav1/mavros/hil/controls
# /uav1/mavros/hil/gps
# /uav1/mavros/hil/imu_ned
# /uav1/mavros/hil/optical_flow
# /uav1/mavros/hil/rc_inputs
# /uav1/mavros/hil/state
# /uav1/mavros/home_position/home
# /uav1/mavros/home_position/set
# /uav1/mavros/imu/data
# /uav1/mavros/imu/data_raw
# /uav1/mavros/imu/diff_pressure
# /uav1/mavros/imu/mag
# /uav1/mavros/imu/static_pressure
# /uav1/mavros/imu/temperature_baro
# /uav1/mavros/imu/temperature_imu
# /uav1/mavros/landing_target/lt_marker
# /uav1/mavros/landing_target/pose
# /uav1/mavros/landing_target/pose_in
# /uav1/mavros/local_position/accel
# /uav1/mavros/local_position/odom
# /uav1/mavros/local_position/pose
# /uav1/mavros/local_position/pose_cov
# /uav1/mavros/local_position/velocity_body
# /uav1/mavros/local_position/velocity_body_cov
# /uav1/mavros/local_position/velocity_local
# /uav1/mavros/log_transfer/raw/log_data
# /uav1/mavros/log_transfer/raw/log_entry
# /uav1/mavros/manual_control/control
# /uav1/mavros/manual_control/send
# /uav1/mavros/mission/reached
# /uav1/mavros/mission/waypoints
# /uav1/mavros/mocap/pose
# /uav1/mavros/mount_control/command
# /uav1/mavros/mount_control/orientation
# /uav1/mavros/obstacle/send
# /uav1/mavros/odometry/in
# /uav1/mavros/odometry/out
# /uav1/mavros/onboard_computer/status
# /uav1/mavros/param/param_value
# /uav1/mavros/play_tune
# /uav1/mavros/px4flow/ground_distance
# /uav1/mavros/px4flow/raw/optical_flow_rad
# /uav1/mavros/px4flow/raw/send
# /uav1/mavros/px4flow/temperature
# /uav1/mavros/radio_status
# /uav1/mavros/rallypoint/waypoints
# /uav1/mavros/rc/in
# /uav1/mavros/rc/out
# /uav1/mavros/rc/override
# /uav1/mavros/setpoint_accel/accel
# /uav1/mavros/setpoint_attitude/cmd_vel
# /uav1/mavros/setpoint_attitude/thrust
# /uav1/mavros/setpoint_position/global
# /uav1/mavros/setpoint_position/global_to_local
# /uav1/mavros/setpoint_position/local
# /uav1/mavros/setpoint_raw/attitude
# /uav1/mavros/setpoint_raw/global
# /uav1/mavros/setpoint_raw/local
# /uav1/mavros/setpoint_raw/target_attitude
# /uav1/mavros/setpoint_raw/target_global
# /uav1/mavros/setpoint_raw/target_local
# /uav1/mavros/setpoint_trajectory/desired
# /uav1/mavros/setpoint_trajectory/local
# /uav1/mavros/setpoint_velocity/cmd_vel
# /uav1/mavros/setpoint_velocity/cmd_vel_unstamped
# /uav1/mavros/state
# /uav1/mavros/statustext/recv
# /uav1/mavros/statustext/send
# /uav1/mavros/target_actuator_control
# /uav1/mavros/time_reference
# /uav1/mavros/timesync_status
# /uav1/mavros/trajectory/desired
# /uav1/mavros/trajectory/generated
# /uav1/mavros/trajectory/path
# /uav1/mavros/vfr_hud
# /uav1/mavros/vision_pose/pose
# /uav1/mavros/vision_pose/pose_cov
# /uav1/mavros/vision_speed/speed_twist_cov
# /uav1/mavros/wind_estimation
# /user_data_async

